apiVersion: v1
kind: Service
metadata:
  name: deltafs-headless
  labels:
    app: deltafs
spec:
  clusterIP: None
  selector:
    app: deltafs
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
